apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:                        
  - name: nginx1
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html1
      mountPath: /usr/share/nginx/html 
  - name: nginx2
    image: nginx
    ports:
    - containerPort: 50
    volumeMounts:
    - name: html2
      mountPath: /usr/share/nginx/html 
    - name: port50
      mountPath: /etc/nginx/conf.d  
  volumes:
    - name: html1
      configMap:
        name: index-html1
    - name: html2
      configMap:
        name: index-html2
    - name: port50
      configMap:
        name: config   

