apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    depi: MyApp2
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        # name: http-web-svc
---      
apiVersion: v1
kind: Service
metadata:
  name: my-service3
spec:
  selector:
    depi: MyApp2
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: ClusterIP      