apiVersion: v1
kind: Pod
metadata:
  name: nginxmulti
spec:
  containers:                          # ----- > containers[0]
  - name: nginxx
    image: nginx
    ports:
    - containerPort: 80
  - name: nginxxxxx                    # ----- > containers[1]
    image: nginx
    ports:
    - containerPort: 80
