apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - name: nginxx
    image: nginx
    ports:
    - containerPort: 80
  - name: ubuntu
    image: ubuntu
    command: ["sleep"]
    args: ["1000"]
