apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels: 
    pod: pod2
spec:
  containers:
  - name: pod2
    image: nginx
    ports:
    - containerPort: 80


    # curl servicename
    # curl servicename.namesace
    # curl servicename.namesace.svc.cluster.local