apiVersion: v1
kind: Pod
metadata:
  name: pod-storage
  namespace: default
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: st
      mountPath: /usr/share/nginx/html
  volumes:
  - name: st
    persistentVolumeClaim:
      claimName: pvc-example