apiVersion: v1
kind: Pod
metadata:
  name: ngi
spec:
  containers:                          # ----- > containers[0]
  - name: nginxx
    image: nginx
    ports:
    - containerPort: 80
  - name: nginxxxxx                    # ----- > containers[1]
    image: nginx
    ports:
    - containerPort: 82
    volumeMounts:
    - name: cm
      mountPath: /etc/nginx/conf.d/ 
  volumes:
  - name: cm
    configMap:
      name: my-config
