# apiVersion: v1
# kind: Service
# metadata:
#   name: sv
# spec:
#   selector:
#     app: nginx
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: sv
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
  externalTrafficPolicy: Local
