apiVersion: v1
kind: Pod
metadata:
  name: podname
spec:
  containers:
  - name: podname
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: cm
      mountPath: /usr/share/nginx/html 
    - name: dm
      mountPath: /etc/nginx/conf.d    
  volumes:
  - name: cm
    configMap:
      name: my-config
  - name: dm
    configMap:
      name: my-con   
