apiVersion: v1
kind: Pod
metadata:
  name: pod-storage
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: st
      mountPath: "/usr/share/nginx/html/"
  volumes:
  - name: st
    persistentVolumeClaim:
      claimName: pvc-example