apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: resource
spec:
  containers:
  - name: pod1
    image: nginx
    resources:
      requests:
        memory: "600Mi"
        cpu: "1"
      limits:
        memory: "600Mi"
        cpu: "1"