apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: resource
spec:
  containers:
  - name: pod2
    image: nginx
    resources:
      requests:
        memory: "500Mi"
        cpu: "1"
      limits:
        memory: "500Mi"
        cpu: "1"