apiVersion: v1
kind: ResourceQuota
metadata:
  name: basic-quota
  namespace: resource
spec:
  hard:
    pods: "2"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi